/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatIntelRouteImport } from './routes/threat-intel'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicatorsRouteImport } from './routes/indicators'
import { Route as IndexRouteImport } from './routes/index'

const ThreatIntelRoute = ThreatIntelRouteImport.update({
  id: '/threat-intel',
  path: '/threat-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorsRoute = IndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indicators': typeof IndicatorsRoute
  '/login': typeof LoginRoute
  '/playbooks': typeof PlaybooksRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indicators': typeof IndicatorsRoute
  '/login': typeof LoginRoute
  '/playbooks': typeof PlaybooksRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indicators': typeof IndicatorsRoute
  '/login': typeof LoginRoute
  '/playbooks': typeof PlaybooksRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/indicators'
    | '/login'
    | '/playbooks'
    | '/settings'
    | '/threat-intel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/indicators'
    | '/login'
    | '/playbooks'
    | '/settings'
    | '/threat-intel'
  id:
    | '__root__'
    | '/'
    | '/indicators'
    | '/login'
    | '/playbooks'
    | '/settings'
    | '/threat-intel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndicatorsRoute: typeof IndicatorsRoute
  LoginRoute: typeof LoginRoute
  PlaybooksRoute: typeof PlaybooksRoute
  SettingsRoute: typeof SettingsRoute
  ThreatIntelRoute: typeof ThreatIntelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threat-intel': {
      id: '/threat-intel'
      path: '/threat-intel'
      fullPath: '/threat-intel'
      preLoaderRoute: typeof ThreatIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicators': {
      id: '/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof IndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndicatorsRoute: IndicatorsRoute,
  LoginRoute: LoginRoute,
  PlaybooksRoute: PlaybooksRoute,
  SettingsRoute: SettingsRoute,
  ThreatIntelRoute: ThreatIntelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
